@startuml
autonumber
title       Client wants to choose payment
actor       Client
participant Application
database    Database
participant "Payment system" as PaymentSystem

ref over Client, Application, Database: Show basket
ref over Client, Application, Database: Authentication
ref over Client, Application, Database: Validate basket
ref over Client, Application, Database: Enter delivery informations
Client -> Application: Show payment page
Application -> Client: Render show payment page
alt Payment method is online
    Client -> Application: Choose payment system
    Application -> PaymentSystem: Redirect to payment system
    PaymentSystem -> Application: Return payment status
    alt Payment is successful
        Application -> Database: Update paidStatus
        Database -> Application: Return paidStatus update
        Application -> Client: Redirect to confirmation page
    else Payment is not successful
        Application -> Client: Redirect to payment page with error
    end
else Payment method is at delivery
    Client -> Application: Choose at delivery
    Application -> Database: Update paidStatus
    Database -> Application: Return paidStatus update
    Application -> Client: Redirect to confirmation page
end

@enduml
